---
- name: Configure Cisco Switch
  hosts: 192.168.20.4
  gather_facts: no
  connection: network_cli
  
  tasks:
    - name: Load variables
      ansible.builtin.include_vars: variables.yaml
    - name: Vlan database
      cisco.ios.ios_config:
        lines:
          - "vlan {{ item.id }}"
          - "name {{ item.name }}"
      loop: "{{vlansnord}}"
    - name: Configure trunk ports
      cisco.ios.ios_config:
        lines:
          - "switchport mode {{ item.mode }}"
          - "switchport trunk allowed vlan {{ item.vlan }}"
          - "no shutdown"
        parents: "interface {{  item.interface  }}"
      loop: "{{Switchnord_ports}}"